# Generated by Django 3.2.6 on 2022-06-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phonenum_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card',
            field=models.IntegerField(choices=[(1, 'Visa'), (2, 'Mastercard'), (3, 'American Express')], default=1),
        ),
    ]
