# Generated by Django 3.2.6 on 2022-07-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_payment_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card',
            field=models.IntegerField(choices=[(1, 'Visa'), (2, 'Mastercard'), (3, 'American Express'), (4, 'Discover'), (5, 'Diners Club'), (6, 'JCB'), (7, 'UnionPay')], default=1),
        ),
    ]
