# Generated by Django 3.2.6 on 2022-07-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_pet_pro_app', '0001_msql_app_order_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_product',
            field=models.URLField(default=None, max_length=350),
            preserve_default=False,
        ),
    ]
