# Generated by Django 3.2.6 on 2022-07-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_pet_pro_app', '0002_added_actual_product_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitBug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_message', models.TextField(max_length=500)),
                ('bug_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='messagebox',
            name='msg',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='missionstatementtopics',
            name='topic',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
