# Generated by Django 3.2.6 on 2022-07-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_pet_pro_app', '0006_removed_url_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actual_product',
            field=models.URLField(max_length=750),
        ),
    ]
