"""
Django settings for power_pet_pro project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('POWER_PET_PRO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True   # Changed on pythonanywhere

ALLOWED_HOSTS = [
    'justindo720.pythonanywhere.com',
    '*',
]

# Application definition

INSTALLED_APPS = [
    # My apps
    'power_pet_pro_app',
    'rest_framework',
    'djoser',
    'rest_framework_simplejwt',
    'users',
    'django_extensions',
    'corsheaders',
    'order',
    'storages',

    # Default Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    # My Django MiddleWare
    # Default Django MiddleWare
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'power_pet_pro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'power_pet_pro.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Default engine no need to change
        'NAME': os.getenv('POWER_PET_PRO_MYSQL_NAME'),  # User & Default database
        'USER': os.getenv('POWER_PET_PRO_MYSQL_USER'),  # User & Default database
        'PASSWORD': os.getenv('POWER_PET_PRO_MYSQL_PASSWORD'),  # Password
        'HOST': os.getenv('POWER_PET_PRO_MYSQL_HOST'),   # Server
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# CorsHeaders
CORS_ORIGIN_WHITELIST = (
    # Cors should not have path meaning no trailing /
    'http://localhost:8080',
    'https://powerpetpro.web.app',
    'https://powerpetpro.firebaseapp.com',
    'https://justindo720.pythonanywhere.com',
)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "content-disposition",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_ROOT = '/home/justindo720/PowerPetProPrivate/static' # Pythonanywhere
STATIC_URL = '/static/'

# Media Files
MEDIA_URL = '/power_pet_pro/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'power_pet_pro_app/media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SJWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=8),
    'ROTATE_REFRESH_TOKENS': True,  # we will get a need refresh token as well
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,


    'AUTH_HEADER_TYPES': ('Bearer', 'JWT'),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'email',
    'USER_ID_CLAIM': 'user_id',

    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
}

# Restframework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,
}

# Djoser Settings
DJOSER = {
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'activate/{uid}/{token}',
    'SEND_CONFIRMATION_EMAIL': True,
    'SEND_ACTIVATION_EMAIL': True,
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND': True,
    'USER_CREATE_PASSWORD_RETYPE': True,
    'LOGIN_FIELD': 'username',
    'SERIALIZERS': {
        'user_create': 'power_pet_pro_app.serializers.MyUserCreationSerializer',
        'user': 'power_pet_pro_app.serializers.MyUserCreationSerializer',
        'user_delete': 'djoser.serializers.UserDeleteSerializer',
    },
}

# Email Config For Sending Emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv('POWER_PET_PRO_EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('POWER_PET_PRO_EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True

# Django Extensions
SHELL_PLUS_PRE_IMPORTS = [
    'from power_pet_pro_app.models import Category, Product, FeedBackQuestions, Feedback, FeedBackAnswers',
    'from order.models import CartItem'
    'from django.contrib.auth.models import User',
    'from users.models import Profile',
    'from faker import Faker',
    'from pprint import pprint'
]

# FRONTEND_BASE_URL = 'http://localhost:8080/'
FRONTEND_BASE_URL = 'https://powerpetpro.web.app/'
AUTH_USER_MODEL = 'users.CustomUser'

STRIPE_SECRET_KEY = os.getenv('POWER_PET_PRO_STRIPE_SECRET_TEST_KEY')

# Google Cloud Storage
from google.oauth2 import service_account

#
GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
    os.path.join(BASE_DIR, 'power-pet-pro-a687ace4203c.json')   # IAM > Keys > Add key > create key > Json
)
DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
GS_BUCKET_NAME = 'powerpetpro'
GS_QUERYSTRING_AUTH = False
GS_FILE_OVERWRITE = False
